### ISSUE TITLE
Clicking on a feature that is currently "selected" by the Search widget, will not update the list

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-polling#115] opened 2015-10-30 17:50 UTC
Clicking on a feature that is currently "selected" by the Search widget, will not update the list

Repo Steps
Open a polling application that has the "layer search configured"
Using the Search box on the left handside. 
Search for a feature in the map. 
Select the feature from the suggestion list
Application will select and zoom to feature

If you click on the selected feature then list will not get updated. 
I would expect once the feature is selected in the layer list that the layer list would update to that feature. 

Enhancement: When you select feature from the Search widget suggestoin list, update the list to reflect the selection

**Comment by allisonmuise** [comment] 2015-10-30 21:26
search result selection graphic blocks the feature in the map.

**Comment by MikeTschudi** [comment] 2015-10-31 00:24
@LindsayThomas, is this the enhancement?

One selects a suggestion
![image](https://cloud.githubusercontent.com/assets/2125181/10860726/f437736c-7f29-11e5-9a2e-7e802710755a.png)

and the collapsed search suggestions list looks like this
![image](https://cloud.githubusercontent.com/assets/2125181/10860646/9a90862e-7f28-11e5-90a1-f9e8fe560f8d.png)

instead of this
![image](https://cloud.githubusercontent.com/assets/2125181/10860744/3cdb99b8-7f2a-11e5-90e2-a0b001f6cd8d.png)

If so, then I'll close this enhancement request and re-create it in the arcgis-js-api repository, which is where the Search dijit lives.

**Comment by allisonmuise** [comment] 2015-11-01 20:09
@MikeTschudi : The issue is that 
1) the details pane does not update to show the info for the feature selected from the search results, and 
2) the feature selected from the search results cannot be clicked/tapped in the map to bring up the details, even after selecting another feature. It looks to me like the selection graphic is blocking interaction with the feature.

Ideally, choosing a feature from the search results should load the details for that feature AND it should still be possible to interact with the feature on the map.

**Comment by allisonmuise** [comment] 2016-01-05 19:26
verified

**Closed by allisonmuise** 2016-01-05 19:26 UTC
Labels: Bug, Installed
