### ISSUE TITLE
Attachements do not upload in IE or Edge but works in Chrome and Firefox

### ISSUE THREAD

**Issue by MarkCooperSDC** [Esri/crowdsource-polling#201] opened 2018-07-05 09:22 UTC
When trying to attach a file to a comment in Internet Explorer or Edge, the upload fails every time. This works fine in other browsers. We have raised this a a call with ESRI UK and they have been able to replicate it both when the feature class is hosted and when coming from an enterprise gdb. It has been raised as BUG-000115151

Is there a way round this that you know, or at least a way the default message can be changed to say the comment has been submitted but the attachment failed?

Thanks
Mark

@allisonmuise

**Comment by allisonmuise** [comment] 2018-07-05 16:08
I'm unable to reproduce the issue. The filed bug will eventually make it's way to me, but if you'd like me to take a look sooner I'll need:
- Operating system
- browser versions where it fails (also - do the same apps work on other browsers?)
- are you able to reproduce this with multiple datasets/maps/apps?
- link to an app that has the issue

**Comment by MarkCooperSDC** [comment] 2018-07-06 09:15
Hi

We have tested uploading in Windows 7, Windows 10, Android and IOS using Chrome, IE, Edge, Safari, Samsung and Firefox browsers. The only combination it doesn’t work on is a Windows OS and either IE (11) or Edge

We have tried using a different data set and we have the same results. We have tested both with data stored in our SDE and hosted on AGOL.

I think I have found you in AGOL so will invited you to the group. We have some limit useage settings on the data so I presume I need to know the first part of the url for the AGOL account you use to enable you to get in?

![chrome](https://user-images.githubusercontent.com/20701486/42370632-2aa1c95e-8105-11e8-9436-e640a33be6f8.jpg)
![ie11](https://user-images.githubusercontent.com/20701486/42370633-2aba3b06-8105-11e8-8cab-8be2e1da63dc.jpg)

**Comment by MarkCooperSDC** [comment] 2018-08-07 13:33
Hi Allison

Following a complaint from a member of the the public, it appears that IE and Edge users can not view attachments other people have uploaded either, which is actually a far more serious issue. Do you have any idea what may be causing this? Everything works fine in Chrome etc.

Many thanks

@allisonmuise

**Comment by allisonmuise** [comment] 2018-08-14 16:17
@MarkCooperSDC The example sent to me from support has the relationship set up between the OBJECTID field of the feature layer and the OBJECTID field of the table. If your data is set up the same way, this is the problem (although it shouldn't work in any browser). This is not a valid relationship. The foreign key (table) field must be a field that supports duplicate values. OBJECTID, FID, GlobalID, etc fields require unique values and cannot be foreign keys. 

I cannot make the application they sent me work in any browser. I still cannot reproduce this issue with applications I create using valid relationships - a GlobalID field on the features (primary key) and a GUID field on the table (foreign key). 

I will reach out to the support analyst to let them know of this issue with their report, and hopefully they can send me a better repro case. I'm unable to access the content you tried to share with me.

**Comment by MarkCooperSDC** [comment] 2018-09-25 15:00
@allisonmuise Sorry for not getting back - the consultation was live so we didn't want to mess with it! The good thing is, we had thousands of comments come in and everything else worked really well (apart from our servers getting hit a bit hard on the last day!) 

It is now closed and it appears that attachments can also not be opened in IE or Edge. Again they work fine in all other browsers we tested. Would you be able to see if you can access them?

https://sdc.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=af73a66186e540abb2cf0918f37a13e1

If you search for site EM6 there will be some attachments.

Thanks
Mark

**Comment by allisonmuise** [comment] 2018-09-25 16:11
@MarkCooperSDC Thanks so much for sharing! I have sent this on to the developer of this app and we are looking into this.

**Comment by allisonmuise** [comment] 2019-03-13 16:52
@MarkCooperSDC Are you able to share the URL to this service so we can confirm this fix? If not, we will close this issue.

**Comment by aparveen** [comment] 2019-03-20 19:31
This issue was not verified by the customer and we will reopen it when more information is provided.

**Closed by aparveen** 2019-03-20 19:31 UTC
Labels: Installed
