### ISSUE TITLE
Add support for filtering

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-polling#213] opened 2019-08-22 13:18 UTC
Add a boolean variable for the "map view" and "push pin" icon when small form factor is being used.

![2019-08-22_9-16-18](https://user-images.githubusercontent.com/2379312/63517905-e288f400-c4bd-11e9-910c-eac2ba598197.png)

True (default setting) - user would see both the map view and the push pin by default
False - user would not see the map view or push pin when the small form factor is present. 

This is needed to support the Special Events workflow and would need to be included in the next AGOL release. 

@jlindemann

**Comment by allisonmuise** [comment] 2019-09-09 18:20
@LindsayThomas What is the issue that is being encountered on phones?

**Comment by jlindemann** [comment] 2019-09-09 18:29
@allisonmuise for Special Events, we are actually using Crowdsource Polling in Ops Dashboard with another webmap.  This allows for filtering via a URL that will filter both the Polling app to the appropriate event and the webmap to show the correct event without seeing the other events.  If you click this view map button you see two maps side by side and gets confusing.  The issue isn't really for phone specifically, but given the size within the dashboard it is factoring to display at that size.

![image](https://user-images.githubusercontent.com/2989767/64556698-35a3d900-d2fd-11e9-8298-39568927f06a.png)

**Comment by allisonmuise** [comment] 2019-09-09 18:39
@jlindemann What functionality is ops dashboard adding to Polling here? I'm trying to understand if there's a larger change we could make to Polling to fully support your workflow rather than making a little change to support embedding in a dashboard, which is outside the intended purpose of Polling.

**Comment by jlindemann** [comment] 2019-09-09 19:00
@allisonmuise - thanks, yes makes sense.  The enhancement would be to have a URL Parameter filter multiple layers inside the webmap for Crowdsource Polling.  Right now the URL parameter filters the comments section to the appropriate layer, which is good but we need a bit more.

Take this URL for example:
https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=fb1000361d954e37a289dcb546e33974&GlobalID=d6bb29e3-05a0-4108-9fce-dba921973769

What we'd ideally want is that GlobalID value to filter multiple layers (Special Event Assets, Special Event Routes, Special Event Areas).  We are using Crowdsource Manager to help manage dozens of events, many of them overlapping.  When an internal stakeholder goes to provide comments, these layers are critical for their comments but need to filter out just for the specified event.   

Right now, dashboard is the mechanism to filter multiple layers but is also giving some additional functionality of filtering road blocks via a custom range to see what planned activity may impact an event.

**Comment by allisonmuise** [comment] 2019-09-09 20:23
Notes from conversation with @jlindemann :

2 filtering mechanisms are needed.

1. Use case: filter multiple layers in a map to show only those features related to a specific incident. Incident ID field may have different names in each layer.

   - need ability to filter multiple layers in the map that contain the same value in a field. The field name may be different across layers.

   - Filter should be specified in URL only - not exposed in the UI. Filtered app will only be accessed via URL and end users should not be able to change the filter, or even be aware of the filtering that is occurring.

   - The only value that should be configurable for this filter is a list of the names of the fields that could contain the common value. These field names should be consolidated into a single URL param such as ?value=1234GUID5678. These field names will need to be user-supplied as they will span multiple layers.

2. Need ability to filter specific layers using specific queries, such as road blocks that fall within a specific date range.

   - each filter is applied to only one layer.

   - filter(s) must be editable in the UI.

   - filters do not need to be reflected in the URL.

   - Perhaps configure using the 'Ask for values' filters defined in the map, with a configuration toggle (off by default) that users can enable to have these filters exposed in the app (backwards compatibility)?

Additional info:
   - Only features that match filters defined by 1 & 2 should be rendered in the map and listed in the panel. 

   - Polling and reference layers should be impacted by the applied filters.

**Comment by allisonmuise** [comment] 2019-10-15 19:50
Additional info for #1 : 
Include additional configuration parameter (disabled by default) that will filter the list of features to only those that meet the criteria of the URL filter.

**Comment by sumitzarkar** [comment] 2019-10-18 06:10
@allisonmuise 



>Use case: filter multiple layers in a map to show only those features related to a specific incident. Incident ID field may have different names in each layer.

As discussed on call we will implement only # 1 in this ticket and here are the details for it:

 - Only one field value needs to be supported 
 - User can pass multiple fields on which the filter need to be applied. it will be an comma separated list
 - User will not pass any layer id in the url as it would be difficult to maintain. In the application we will check if the given field is available in the layer then we will apply filter for that field with the given value
- So to add this functionality app will accepts two url parameters 
    1. value
    2. fields

- Sample Url:
  - https://xyz.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=fxxxxxxxxxxxxxxxxxxxxxxxxxxx3974&value=d6bb29e3-05a0-4108-9fce-dba921973769&fields=GlobalId,ParentGlobalId,Pid,ProjectID


>Additional info for #1 :
Include additional configuration parameter (disabled by default) that will filter the list of features to only those that meet the criteria of the URL filter.

We don't think we need to add this additional parameter as user can use the existing configuration parameter "showAllFeatures" if this is set to false the list will display only those features in map.

Please let us know if we are missing anything

**Comment by allisonmuise** [comment] 2019-10-22 16:52
@sumitzarkar I think we can remove the field list from the URL. Thsi list can be defined in the configuration of the application. Only the value needs to be in the URL.

**Comment by sumitzarkar** [comment] 2019-10-22 17:41
@allisonmuise 

OK, we can add "Multiple Layer and Field Selector" in the configuration so that user can configure multiple fields from multiple layers.

**Comment by allisonmuise** [comment] 2019-11-14 17:02
@jlindemann This enh has been installed into devext. Could you take a look and confirm that it's working as expected?

**Comment by jlindemann** [comment] 2019-11-14 19:51
@allisonmuise I'm confused and can't seem to get this to work.

I have this map shared public
https://solutions.mapsdevext.arcgis.com/home/item.html?id=249d2a82932f41f9b58f93c402fff7f4
In config for the app I made a URL Parameter called "eventid".  Even setting this to the ObjectID for the layer (special events) doesn't work.  I add this to the end of the URL and get an "Item does not exist or is inaccessible error".

I'm also confused on the config tab "Select search layers and fields".  Is this supposed to be for the URL parameter to find other fields or to search within the address bar?  I tried adding the same eventid variable here and turned on appropriate names but was not getting anything back.

**Comment by allisonmuise** [comment] 2019-11-14 21:01
@sumitzarkar Could you take a look at the config panel changes for this capability? I think there is something funny going on with how the parameters are defined in the JSON. In the UI there is a text box at the top of the tab, but it doesn't have a label and doesn't appear to be connected to a value i the JSON. Is this where we should define the name of the URL parameter?

When referencing a value that contains spaces (&paramname=My Party) should we use %20 in the spaces? (&paramname=My%20Party)

**Comment by sumitzarkar** [comment] 2019-11-15 06:46
@allisonmuise 

>In the UI there is a text box at the top of the tab, but it doesn't have a label and doesn't appear to be connected to a value i the JSON. Is this where we should define the name of the URL parameter?

- This textbox is added by mistake and we will update the json to remove it.

- As discussed earlier we are only supporting one URL parameter i.e. **value**

- User can select the layers and fields on which the filter needs to be applied:
![image](https://user-images.githubusercontent.com/9443956/68921959-5aef1080-07a0-11ea-882f-2afd9ef57369.png)

- Sample Url:

https://xyz.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=fxxxxxxxxxxxxxxxxxxxxxx3974&value=d6bb29e3-xxxx-xxxx-9fce-dba921973769

- When the app is loaded it will look for **value** parameter in URL and use it to apply the filters on the layers and fields selected in the above configuration.

**Comment by ashishchoure** [comment] 2019-11-15 13:27
@allisonmuise 

We have removed the text box and sent a new [pull request](https://github.com/Esri/crowdsource-polling/pull/221). Please have a look at it and let me know if you find any issues.

**Comment by allisonmuise** [comment] 2019-11-15 17:49
@ashishchoure Thanks - This is working well now. What would be the LOE to have the details open immediately when there is only one item in the list of features? If the list is filtered to one item it seems silly to have users do the extra click to open it.

**Comment by allisonmuise** [comment] 2019-11-15 17:53
also - instead of the static parameter name 'value', could we use the existing user-supplied name (customUrlParam) on the Custom URL Parameter tab? Users will not use both types of URL params, and I will be moving all the URL param options to a single tab so this will be more intuitive for users.

**Comment by ashishchoure** [comment] 2019-11-18 12:14
@allisonmuise 

> @ashishchoure Thanks - This is working well now. What would be the LOE to have the details open immediately when there is only one item in the list of features? If the list is filtered to one item it seems silly to have users do the extra click to open it.

- This will require some research to make sure we have covered all the cases. Here are some of the cases we will have to consider :
  -  "**Filter list by map**" is enabled and only one feature is within the extent
  -  When only one feature is passing the criteria via values provides from URL param
  -  When only one feature is passing the criteria via values provides from URL param and show related records flag is set to true

We think this change requires good amount of effort for listing down the cases, implementation and testing.
 
Are you expecting this change in current release ?

**Comment by ashishchoure** [comment] 2019-11-18 12:17
@allisonmuise 

> also - instead of the static parameter name 'value', could we use the existing user-supplied name (customUrlParam) on the Custom URL Parameter tab? Users will not use both types of URL params, and I will be moving all the URL param options to a single tab so this will be more intuitive for users.

- We can easily implement this change.
- So, instead of checking for static `value` url parameter, we will check if `customUrlParam` is configured.
- If yes then we will apply the value supplied in URL to all the configured layers and fields which are listed in **Select layers and fields for filtering** tab.

**Comment by allisonmuise** [comment] 2019-11-18 16:03
@ashishchoure 
re: customUrlParam - Let's proceed with this change for this release. Please note that there is an updated config panel in the develop branch.

re: one item in the list: Yes, I would like this for this release if at all possible. Would it be more reasonable to only handle this case _When only one feature is passing the criteria via values provides from URL param_ for this release? 

This scenario is going to be featured in a solution that will be released in January and the URL params will be set up to only ever return one feature so the extra click will be very obvious (and annoying). We can decide if we need/want this behavior for the other scenarios at a future release.

**Comment by ashishchoure** [comment] 2019-11-19 12:13
@allisonmuise 

We will implement the change to show the feature details panel when only one feature is passing the criteria via values provides from URL param.

**Comment by allisonmuise** [comment] 2019-11-27 20:26
@jlindemann can you take another look at this on devext?

**Comment by jlindemann** [comment] 2019-11-27 21:18
@allisonmuise hmmmm, I can't seem to get this to work now.  Even with going back to the "value" keyword (and explicitly stating I want that variable name in the config panel, it doesn't seem to filter out

https://solutions.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=b3688a67e23e4127ae0eac4ac7ec9b25&value=6

**Comment by allisonmuise** [comment] 2019-12-03 18:13
@jlindemann The build has been fixed. it looks like it's working now to me. Can you check with your data?

**Comment by jlindemann** [comment] 2019-12-03 19:23
@allisonmuise yes this looks good!  thanks!  Didn't close yet, wasn't sure if you had anything else you wanted.  Can the config text be run onto more new lines?  It is not really intuitive to expand the app to just read the text
![image](https://user-images.githubusercontent.com/2989767/70082441-a9394780-15c7-11ea-8f05-32d915f24e0d.png)

**Comment by allisonmuise** [comment] 2019-12-03 19:52
@jlindemann Unfortunately that's not something I can control. I'm guessing there is a long layer name or something further down in the panel that is forcing the text container to be out wider than the default panel width.

**Closed** 2019-12-03 19:53 UTC
Labels: Enhancement, High, Verified, test case
