### ISSUE TITLE
Error When Adding a Comment 

### ISSUE THREAD

**Issue by vmagnis** [Esri/crowdsource-polling#136] opened 2016-06-03 20:24 UTC
I am getting this error when a comment button is used. 

"[OBJECTID]
A required field is neither initialized nor in the form"

Thanks 

Vicki

**Comment by allisonmuise** [comment] 2016-06-03 22:47
Hi Vicki,

Sounds like a field that does not accept null values either doesn't have a default value or isn't exposed in the comment form. If you've got all required fields exposed or set with default values, try contacting Esri Support Services or your distributor for help resolving this error message.

Thanks,
-Allison

**Comment by vmagnis** [comment] 2016-06-06 12:25
It's an ObjectID field so it's an auto increment  field. And it allows me to enter comments and saves them and the ObjectID field gets updated but I get that error message.

**Comment by allisonmuise** [comment] 2016-06-08 16:28
@vmagnis I can't reproduce this issue. Please contact Esri Support Services or your distributor. They will have the resources to help you troubleshoot this issue.

**Closed by allisonmuise** 2016-06-08 16:28 UTC
