### ISSUE TITLE
Search Layer

### ISSUE THREAD

**Issue by MarkCooperSDC** [Esri/crowdsource-polling#158] opened 2016-10-06 15:27 UTC
Hi

I using this template in AGOL and the Search box uses the ESRI World Geocoder (or ALL of the geocoders set up on the Organisation) and ONE field from the layer used to form the questions.

My question are:

1) Can it be limited to only look at certain geocoders
2) How can you tell it which field in the layer it uses to search?

Many thanks

@allisonmuise

**Comment by allisonmuise** [comment] 2016-10-06 16:38
@MarkCooperSDC : This app uses the map's search settings. If you'd like the app to search additional fields, open the Settings tab on the Details page for the map. Enable the layer search and choose which layers and fields you'd like included. I see that it is searching a field by default, even when the Layer search is disabled. I need to investigate this further.

The geocoders used should be your organization's geocoders.

**Comment by MarkCooperSDC** [comment] 2016-10-07 13:33
Thanks @allisonmuise .I have configured the search to work for the layers. However I am now having major problems with the ESRI World Geocoder. When you search for an address, it appears from a pick list but when you select the option it fails to find the address. Have you seen this behaviour before?
![crowdsource1](https://cloud.githubusercontent.com/assets/20701486/19191458/74391786-8c9a-11e6-84f9-d1d5b02ad898.png)
![crowdsource2](https://cloud.githubusercontent.com/assets/20701486/19191473/879033dc-8c9a-11e6-971f-9352ebbb9784.png)

**Comment by allisonmuise** [comment] 2016-10-07 15:52
@MarkCooperSDC : Hmm...I haven't seen that. Would you mind contacting Support with about this? They have better resources for troubleshooting than GitHub :) When they pin down the cause they'll make sure it gets reported to me if it's a Polling issue or the AGOL team if it's a geocoder issue.

**Comment by allisonmuise** [comment] 2016-11-23 16:11
closing this as no further details provided

**Closed by allisonmuise** 2016-11-23 16:11 UTC
